"""YOLO label grouping helpers for mapping model outputs into coarse carbon categories."""

YOLO_LABELS = {
    0: "apple",
    1: "asparagus",
    2: "bacon",
    3: "baked potatoes",
    4: "banana",
    5: "beans",
    6: "black bean",
    7: "blueberries",
    8: "board",
    9: "boiled egg",
    10: "bowl",
    11: "bread",
    12: "breaded",
    13: "brocolis",
    14: "cabbage",
    15: "cabidela rice",
    16: "cake",
    17: "carrot",
    18: "cereals",
    19: "cheese",
    20: "chicken",
    21: "chicken steak",
    22: "chips",
    23: "chorizo",
    24: "coffee",
    25: "coffee cup",
    26: "cucumber",
    27: "cup",
    28: "cutlet",
    29: "fish",
    30: "fish hake",
    31: "fork",
    32: "french fries",
    33: "fried cod",
    34: "fried egg",
    35: "garbage",
    36: "gelatin",
    37: "grape",
    38: "greens",
    39: "grilled chop",
    40: "grilled steak",
    41: "ham",
    42: "knife",
    43: "lasagna",
    44: "lettuce",
    45: "lime",
    46: "mashed potatoes",
    47: "meatballs",
    48: "melon",
    49: "minced meat",
    50: "mushrooms",
    51: "mussel",
    52: "olives",
    53: "omelet",
    54: "onion",
    55: "pasta",
    56: "pineapple",
    57: "pizza",
    58: "plate",
    59: "pork",
    60: "pork belly",
    61: "pork intestines",
    62: "pork loin",
    63: "rice",
    64: "salmon",
    65: "scrambled eggs",
    66: "scrambled eggs with bacon",
    67: "soup",
    68: "soupbowl",
    69: "spaghetti",
    70: "spoon",
    71: "steak",
    72: "steaks with mushrooms",
    73: "stewed veal",
    74: "strawberry",
    75: "toasted bread",
    76: "tomato",
    77: "tuna",
    78: "tuna with mushrooms",
    79: "tuna with pasta",
    80: "turkey steak",
    81: "vegetables",
    82: "water",
    83: "water cup",
    84: "watermelon",
}

NON_FOOD_LABELS = {
    "board",
    "bowl",
    "coffee cup",
    "cup",
    "fork",
    "garbage",
    "knife",
    "plate",
    "soupbowl",
    "spoon",
    "water",
    "water cup",
}

YOLO_CATEGORY_MAP = {
    "rice": [
        "cabidela rice",
        "rice",
    ],
    "vegetable": [
        "asparagus",
        "baked potatoes",
        "beans",
        "black bean",
        "brocolis",
        "cabbage",
        "carrot",
        "cucumber",
        "french fries",
        "greens",
        "lettuce",
        "mashed potatoes",
        "mushrooms",
        "olives",
        "onion",
        "tomato",
        "vegetables",
    ],
    "chicken": [
        "chicken",
        "chicken steak",
        "turkey steak",
    ],
    "fish": [
        "fish",
        "fish hake",
        "fried cod",
        "mussel",
        "salmon",
        "tuna",
        "tuna with mushrooms",
        "tuna with pasta",
    ],
    "egg": [
        "boiled egg",
        "fried egg",
        "omelet",
        "scrambled eggs",
        "scrambled eggs with bacon",
    ],
}

UNMAPPED_EDIBLE_LABELS = [
    "apple",
    "bacon",
    "banana",
    "blueberries",
    "bread",
    "breaded",
    "cake",
    "cereals",
    "cheese",
    "chips",
    "chorizo",
    "coffee",
    "cutlet",
    "gelatin",
    "grape",
    "grilled chop",
    "grilled steak",
    "ham",
    "lasagna",
    "lime",
    "meatballs",
    "melon",
    "minced meat",
    "pasta",
    "pineapple",
    "pizza",
    "pork",
    "pork belly",
    "pork intestines",
    "pork loin",
    "soup",
    "spaghetti",
    "steak",
    "steaks with mushrooms",
    "stewed veal",
    "strawberry",
    "toasted bread",
    "watermelon",
]


def get_category_for_label(label_name: str) -> str | None:
    normalized = label_name.strip().lower()
    for category, labels in YOLO_CATEGORY_MAP.items():
        if normalized in labels:
            return category
    return None
